import requests
import uuid

BASE_URL = "http://localhost:3000"
AUTH = ("tomato0924@gmail.com", "111111")
HEADERS = {"Content-Type": "application/json"}
TIMEOUT = 30

def test_group_creation_owner_membership_and_invite_code_uniqueness():
    created_group_ids = []
    try:
        # Step 1: Create a new group
        group_name = f"test-group-{uuid.uuid4()}"
        create_payload = {
            "name": group_name,
            "description": "Test group for owner membership and invite code uniqueness"
        }
        resp_create = requests.post(
            f"{BASE_URL}/groups",
            auth=AUTH,
            headers=HEADERS,
            json=create_payload,
            timeout=TIMEOUT
        )
        assert resp_create.status_code == 201, f"Failed to create group: {resp_create.text}"
        group = resp_create.json()
        group_id = group.get("id")
        invite_code_1 = group.get("invite_code")
        owner_id = group.get("owner_id")
        created_group_ids.append(group_id)
        assert group_id is not None, "Group ID missing in response"
        assert invite_code_1 is not None, "Invite code missing in response"
        assert owner_id is not None, "Owner ID missing in response"
        
        # Step 2: Verify owner is automatically a member
        resp_members = requests.get(
            f"{BASE_URL}/groups/{group_id}/members",
            auth=AUTH,
            headers=HEADERS,
            timeout=TIMEOUT
        )
        assert resp_members.status_code == 200, f"Failed to list group members: {resp_members.text}"
        members = resp_members.json()
        owner_is_member = any(m.get("user_id") == owner_id for m in members)
        assert owner_is_member, "Group owner is not a member, trigger add_owner_to_group failed"
        
        # Step 3: Attempt to create another group with the same invite code (simulate uniqueness constraint)
        # Since invite_code is normally generated by backend, we simulate this by forcibly using same invite code if API allows
        # If API disallows invite_code field, we skip direct duplication and create two groups expecting unique invite codes
        # So here, create another group and verify invite code is unique
        group_name_2 = f"test-group-{uuid.uuid4()}"
        resp_create2 = requests.post(
            f"{BASE_URL}/groups",
            auth=AUTH,
            headers=HEADERS,
            json={"name": group_name_2, "description": "Second test group"},
            timeout=TIMEOUT
        )
        assert resp_create2.status_code == 201, f"Failed to create second group: {resp_create2.text}"
        group2 = resp_create2.json()
        group_id_2 = group2.get("id")
        invite_code_2 = group2.get("invite_code")
        created_group_ids.append(group_id_2)
        assert invite_code_2 is not None, "Second invite code missing"
        assert invite_code_2 != invite_code_1, "Invite code is not unique; uniqueness constraint failed"
        
        # Step 4: Attempt to create a group with a duplicate invite code manually if API supports it
        # Try to forcibly set same invite code (assuming API allows override, else skip)
        duplicate_invite_code_payload = {
            "name": f"dup-invite-group-{uuid.uuid4()}",
            "description": "Forced duplicate invite code test",
            "invite_code": invite_code_1  # Forcing duplicate, to test constraint enforcement
        }
        resp_dup = requests.post(
            f"{BASE_URL}/groups",
            auth=AUTH,
            headers=HEADERS,
            json=duplicate_invite_code_payload,
            timeout=TIMEOUT
        )
        # Expect failure status code 400 or 409 for uniqueness constraint error
        assert resp_dup.status_code in (400, 409), f"Duplicate invite code not rejected: {resp_dup.text}"
        
    finally:
        # Cleanup created groups
        for gid in created_group_ids:
            try:
                requests.delete(
                    f"{BASE_URL}/groups/{gid}",
                    auth=AUTH,
                    headers=HEADERS,
                    timeout=TIMEOUT
                )
            except Exception:
                pass

test_group_creation_owner_membership_and_invite_code_uniqueness()